<h2>Was soll das Ganze?</h2>
<div class="subcontent">
	<p>Viele haben das Problem, dass sie parallel oder in wöchentlichen Abständen Serien schauen, aber dann nicht mehr genau wissen wo sie stehen geblieben sind. Dafür soll diese Seite Abhilfe schaffen. Auf dieser Seite kann man Serien anlegen, eigenen Listen hinzufügen und dort die aktuelle Folge verwalten.</p>
	<p><strong>Hinweis:</strong> Diese Webseite funktioniert nur richtig in modernen Browsern (HTML5 & CSS3 fähig) und ist mit deaktiviertem Javascript nicht bedienbar!</p>
</div>
