<?php 
	$this->headTitle("Serie bearbeiten");
?>
<?php
	if($this->form != null) {
?>
<h2>Serie bearbeiten</h2>
<div class="subcontent">
<?php
		$image_id = $this->currentSerieImageId;
		
		if($image_id == null) {
			$image_id = 0;
		}
		
		$html_image = $this->partial('partial/html_image.phtml', array(
			'src' => 'image/index/imageid/'.$image_id.'/imagetype/small/imagemode/proportional',
			'alt' => 'Momentanes Serien Bild')
		);
		echo $html_image;
		echo $this->form;
?>
</div>
<?php
	}
?>