<?php 
	$this->headTitle($this->serie['name']);
?>
<h2>Seriendetails</h2>
<div class="singleserie subcontent">
<?php 
	if($this->addToListForm != null){
		echo $this->addToListForm;
	}
	echo $this->showSerie($this->serie, $this->ser_genres);
?>
</div>
<?php 
	if($this->comments != null) {
?>
<h2>Kommentare</h2>
<?php
	}
?>
<div id="comments">
<?php
	if($this->comments != null) {
		if($this->paginator != null) {
			echo $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator_search.phtml');
		}
?>
	<div class="subcontent">
	<?php
		echo $this->showComments($this->comments);
	?>
	</div>
<?php
		if($this->paginator != null) {
			echo $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator_search.phtml');
		}
	}
?>
<?php
	if($this->commentForm != null) {
?>
<h2>Meinung hinterlassen</h2>
	<div class="subcontent">
	<?php
		echo $this->commentForm;
	?>
	</div>
<?php
	}
?>
</div>

