<?php
    echo $this->doctype()."\n"; 
?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
	echo $this->headTitle(); 
	echo $this->headLink()
		->appendStylesheet($this->baseUrl().'/styles/style.css')
		->appendStylesheet($this->baseUrl().'/jquery/css/ui-lightness/jquery-ui-1.10.3.custom.css')
		->appendStylesheet($this->baseUrl().'/fancybox/jquery.fancybox.css');
        
	
?> 
	  <script>
		var baseUrl = "<?php echo $this->baseUrl() ?>";
	  </script>
<?php 
	echo $this->jQuery(); 
	echo $this->headScript()
		->appendFile($this->baseUrl().'/fancybox/jquery.fancybox.js', 'text/javascript'); 
?>
	<script type="text/javascript">
		$(document).ready(function() {
			$(".fancybox").fancybox({
				'type' : 'image'
			});
			
			$('header nav, header h1 a').tooltip();
			
			$('#main').hide();
			$('#main').fadeIn();
		});
	</script>
 </head>
<body>
	<header id="header">
		<div class="inline">
			<h1><a title="Startseite" href="<?php echo $this->baseUrl() ?>">Serienlist</a></h1>
			<nav id="user_navigation">
				<?php 
					echo $this->navigation()->menu()->renderMenu($this->user_menu); 
				?>
			</nav>
			<nav id="main_navigation">
				<?php 
					$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
					$page = null;
					
					if($controller == 'serie') {
					$page = $this->main_menu->findOneByController($controller);
					}
					
					if($page != null) {
						$page->setActive();
					}
					
					echo $this->navigation()->menu()->renderMenu($this->main_menu); 
				?>
			</nav> 
		</div>
	</header>
	
	<div id="main">
		<?php 
			echo $this->layout()->content;
		?>
	</div>
	<footer>
		<p>
			<?php
				echo $this->partial('partial/html_anchor.phtml', array(
					'text' => $this->partial('partial/html_image.phtml', array(
						'src' => 'content/jquery.png', 
						'width' => '204', 
						'height' => '51', 
						'alt' => 'jQuery')
					),
					'href' => 'http://jquery.com',
					'noescape' => true,
					'nobaseurl' => true
				));
				echo $this->partial('partial/html_anchor.phtml', array(
					'text' => $this->partial('partial/html_image.phtml', array(
						'src' => 'content/jquery-ui.png', 
						'width' => '211', 
						'height' => '51', 
						'alt' => 'jQuery UI')
					),
					'href' => 'http://jqueryui.com/',
					'noescape' => true,
					'nobaseurl' => true
				));
				echo $this->partial('partial/html_anchor.phtml', array(
					'text' => $this->partial('partial/html_image.phtml', array(
						'src' => 'content/zend-framework.png', 
						'width' => '165', 
						'height' => '51', 
						'alt' => 'Zend Framework')
					),
					'href' => 'http://framework.zend.com/',
					'noescape' => true,
					'nobaseurl' => true
				));
			?>
		</p>
		<p>2013 &copy; by Florian Vogelpohl &amp; Stefan Wolf - <a href="<?php echo $this->baseUrl() ?>/index/impressum">Impressum</a></p>
		<p>Bilder von <a href="http://sxc.hu">sxc.hu - Free Stock Photos</a> und <a href="http://openiconlibrary.sourceforge.net/">Open Icon Library</a></p>
	</footer>
</body>
</html>